# This port needs to be open to the players
# This field has no default value, manual set is required.
port:

# Provides the address start for address for the resource pack.
# If this is field is blank, it will use defined ip in server.properties, or the program ipv4.
serverAddress:

# Message sent to the players when sending the resource pack
prompt: "<bold>Accept</bold> our resource pack to have the <gold>right</gold> server experience!"

# Kicks the players if they refuse the resource pack.
# Leave this field blank to avoid kick.
kickOnRefuseMessage: |
  <red>Resource pack refused.</red> If you didn't mean to, go to your server list,edit that server,
  and change the <aqua>`Server Resource Packs`</aqua> option to <gold>`Enabled`</gold>.

# Kicks ths players if they had problems downloading the resource pack.
# This is generally a server problem.
# Leave this field blank to avoid kick.
kickOnFailMessage: |
  <red>Failed to download resource pack</red>, error code: <gold><error_code></gold>.

# The texture pack loader, called every time that the resource pack is loaded by the plugin.
# Each type has their own fields.
# If any error occurs while running the loader, the resource pack sending will be disabled, waiting to another reload
# to try load the resource pack again.
loader:
  ### === Example for `Manual` type. ===

  ### It uses an existing folder of any provided path.
  type: Manual

  ### Relative to the server root folder.
  folder: "plugins/ResourcePackLoader/Manual Pack/"

  ### === End of `Manual` type example.



  ### === Example for `Merged` type. ===

  ### It merges data from many types of loaders.
  ### If there is some error in any loader apply, an error will be thrown.
  # type: Merged

  ### This is a list, for each entry you need to specify the values of the desired loader.
  ### See their how to configure each type in the examples above.
  ### For overriding cases, loaders on the top of the list have major priority, this is,
  ### their files will replace the other files, and a log in console will be sent.
  # loaders:
  #   - type: Manual
  #     folder: "plugins/ResourcePackNoUpload/Manual Pack/"
  #   - type: Manual
  #     folder: "plugins/ModelEngine/resource pack/"
  ### === End of `Merged` type example.
