# Message sent to the players when sending the resource pack
prompt: "§lAccept§r our resource pack to have the §6best§r server experience!"

# Kicks the players if they refuse the resource pack.
# Leave this field blank to avoid kick.
kickOnRefuseMessage: >
  §cResource pack refused.§r If you didn't mean to, go to your server list, edit that server, \
  and change the §bServer Resource Packs§r option to §6Enabled§r.

# Kicks ths players if they had problems downloading the resource pack.
# This is generally a server problem.
# Leave this field blank to avoid kick.
kickOnFailMessage: |
  §cFailed to download resource pack§r, error code: §6<error_code>§r.

# The texture pack loader, called every time that the resource pack is loaded by the plugin.
# Each type has their own fields.
# If any error occurs while running the loader, the resource pack sending will be disabled, waiting to another reload
# to try load the resource pack again.
loader:
  ### === Example for `Manual` type. ===

  ### It uses an existing folder of any provided path.
  type: Manual

  ### Relative to the server root folder.
  folder: "plugins/ResourcePackNoUpload/Manual Pack/"

  ### === End of `Manual` type example.



  ### === Example for `Download` type. ===

  ### Downloads the resourcepack from a link.
  ### At first, it would be somewhat against the plugin's purpose, but this loader also
  ### supports http headers for the download request, allowing you to download the
  ### resource,  pack with private keys.
  # type: Download

  ### The link for the download.
  # url: https://www.googleapis.com/drive/v3/files/FILE_ID?alt=media
  ### Optional field, this is a list of headers, with their keys and values, Here we
  ### are calling the Google API, and passing a required token to download the file.
  # headers:
  #   - key: "Authorization"
  #     value: "Bearer drive_api3213xih32i9DASKxE83hd9203f1930c0ll-d1v3-t0k3n2389"

  ### === End of `Download` type example.



  ### === Example for `WithMovedFiles` type. ===

  ### Move files from a directory, to another. Supports unknown paths, for they use `?`.
  # type: WithMovedFiles

  ### The folder contents to be moved.
  ### For this example, the download (see more loader information below) result for
  ### the loader link would be something like:
  ### `Robsutar-super-cool-pack78HN3278gj32d/assets/minecraft...`
  ### We will use this first folder as origin, ignoring their name.
  # folder: "?/"

  ### The folder destination, here we are using the resource pack root.
  # destination: ""

  ### This can be any loader, For this loader example we are using a release in GitHub,
  ### with Fine-grained personal  access token, with reading permissions. Depending on
  ### the release, the content of the resource pack can be inside another download file,
  ### we use WithMovedFiles to adjust this.
  # loader:
  #   url: https://api.github.com/repos/Robsutar/super-cool-pack/zipball
  #   headers:
  #     - key: "Authorization"
  #       value: "Bearer github_pat_uS78ih32i9DASKxE83hd9203f1930c0ll-g1t-t0k3n2389"
  #     - key: "Accept"
  #       value: "application/vnd.github.v3+json"

  ### === End of `WithMovedFiles` type example.


  ### === Example for `WithDeletedFiles` type. ===

  ### Ignore the files of the loader if they match with a provided path.
  # type: WithDeletedFiles

  ### The path to ignored, supports glob file matching. In this example, we delete all
  ### files that ends with `.md`.
  # toDelete: "**.md"
  ### To ignore all the files of a directory:
  # toDelete:  "assets/all_inside_me_will_be_deleted/**/*"
  ### To ignore a file a file:
  # toDelete:  "assets/minecraft/i_will_be_deleted.txt"

  ### This can be any loader, For this loader example we are using simple Manual loader.
  # loader:
  #   type: Manual
  #   folder: "plugins/ResourcePackNoUpload/Manual Pack/"

  ### === End of `WithDeletedFiles` type example.


  ### === Example for `Merged` type. ===

  ### It merges data from many types of loaders.
  ### If there is some error in any loader apply, an error will be thrown.
  # type: Merged

  ### This is a list, for each entry you need to specify the values of the desired loader.
  ### See their how to configure each type in the examples above.
  ### For overriding cases, loaders on the top of the list have major priority, this is,
  ### their files will replace the other files, and a log in console will be sent.
  # loaders:
  #   - type: Manual
  #     folder: "plugins/ResourcePackNoUpload/Manual Pack/"
  #   - type: Manual
  #     folder: "plugins/ModelEngine/resource pack/"
  ### === End of `Merged` type example.
