name: ResourcePackNoUpload
version: '${project.version}'
main: com.robsutar.rnu.ResourcePackNoUpload
api-version: '1.21'
description: Send your resource pack, without uploading it
authors: [ Robsutar ]
