main: "${PACKAGE}.${NAME}"
name: "${NAME}"
version: "${VERSION}"
description: Send your resource pack, without uploading it
authors: [ Robsutar ]

# Mark the plugin as 1.13 compatible to avoid CB having to perform quite as much unnecessary
# remapping when the plugin is loaded. Note that despite what this setting might otherwise imply,
# LP is still compatible with pre-1.13 releases.
api-version: 1.13

commands:
  resourcepacknoupload:
    usage: "rnu reload"
    permission: "resourcepacknoupload.admin"
    aliases: [ "rnu" ]
    description: "Used to reload the rnu configuration and apply the loader again."