# Message sent to the players when sending the resource pack
prompt: "§lAccept§r our resource pack to have the §6best§r server experience!"

# Kicks the players if they refuse the resource pack.
# Leave this field blank to avoid kick.
kickOnRefuseMessage: >
  §cResource pack refused.§r If you didn't mean to, go to your server list, edit that server, \
  and change the §bServer Resource Packs§r option to §6Enabled§r.

# Kicks ths players if they had problems downloading the resource pack.
# This is generally a server problem.
# Leave this field blank to avoid kick.
kickOnFailMessage: |
  §cFailed to download resource pack§r, error code: §6<error_code>§r.

# Delay in ticks to send the resource pack for the player at their server join.
sendingDelay: 10

# Delay in ticks to resend the resource pack if had no response.
# NOTE: for proxies, in older minecraft version, the resending is not that well performed, in those cases, a higher
# sendingDelay is preferred.
resendingDelay: 40

# The texture pack loader, called every time that the resource pack is loaded by the plugin.
# Each type has their own fields.
# If any error occurs while running the loader, the resource pack sending will be disabled, waiting to another reload
# to try load the resource pack again.
loader:
  # In this example we are using a simple loader file, check all the loaders types here:
  # https://github.com/Robsutar/resource-pack-no-upload/?tab=readme-ov-file#creating-resource-pack-loader
  type: Manual
  folder: "plugins/ResourcePackNoUpload/Cool Folder/"
